"""
Canonical event types used throughout TXN.
"""

NATIVE_TRANSFER = "NATIVE_TRANSFER"
INTERNAL_TRANSFER = "INTERNAL_TRANSFER"

ERC20_TRANSFER = "ERC20_TRANSFER"
ERC721_TRANSFER = "ERC721_TRANSFER"
ERC1155_TRANSFER = "ERC1155_TRANSFER"

GAS_FEE = "GAS_FEE"

UNKNOWN = "UNKNOWN"
